# Generated by Django 4.0 on 2023-11-13 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='login_id',
            new_name='username',
        ),
    ]
